# Generated by Django 2.2.5 on 2020-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summary', models.TextField(default='null')),
                ('contact', models.TextField()),
            ],
        ),
    ]
