# Generated by Django 2.2.5 on 2020-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('decription', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('summary', models.TextField(default='null')),
            ],
        ),
    ]
